### ISSUE TITLE
Step size increase not effective when viewing PDFs in Chrome.

### ISSUE THREAD

**Issue by thedanyes** [galambalazs/smoothscroll#100]
As described in the title.  I use the smooth scrolling extension to increase the default step size, and to increase the acceleration scale.  It works great on web sites, but stops working when viewing a PDF in Chrome.

If it matters, I'm running  43.0.2357.45 beta (64-bit) on Linux Kernel 3.19.3-031903-lowlatency x86_64.

**Comment by galambalazs** [comment]
There is no smooth scrolling when using the built in PDF viewer at all.

It's not just the step size, the script cannot intercept and alter scrolling on those pages.

(The reason is that the PDF viewer acts like an event trap/black hole)
