### ISSUE TITLE
A method to check if the extension is installed

### ISSUE THREAD

**Issue by raeesiqbal** [galambalazs/smoothscroll#110]
There should be an method to check if the smoothscroll extension has been installed, so that, we don't load the website version of smoothscroll or any other plugin.
Here are some examples, [Check if user has a Chrome extension installed](http://stackoverflow.com/questions/6293498/check-whether-user-has-a-chrome-extension-installed)

**Comment by galambalazs** [comment]
Do you experience a conflict of some sort?

**Comment by raeesiqbal** [comment]
never mind.

**Comment by galambalazs** [comment]
I think this issue raises a valid question, I do wonder how SS works when both the website is embedding it and the extension is installed. I would assume whichever runs first wins (because the preventDefault makes the other one ignore wheel events).

**Comment by raeesiqbal** [comment]
I tried it and it worked just fine. I think the extension suppressed the other one.

**Comment by galambalazs** [comment]
Thanks for the feedback. Yeah I thought it should work :)

**Comment by raeesiqbal** [comment]
Great plugin by the way, thanks much :+1:
