### ISSUE TITLE
Wheel event fires repeatedly even when disabled for a site

### ISSUE THREAD

**Issue by pbfy0** [galambalazs/smoothscroll#114]
Even when a site is blacklisted in the extension settings, the wheel event still fires multiple times per scroll notch on that site.

**Comment by galambalazs** [comment]
I'm not sure I understand.

SmoothScroll doesn't fire any `wheel` events.

So even when it's *enabled* the 1/wheel event per tick remains the same.

**Comment by pbfy0** [comment]
I did some more checking, and I realized that the problem is that I blacklisted the page, but not the frame within it that actually had the event listener. It was listening for `scroll` events. So, this isn't really an issue with smoothscroll. However, maybe blacklisting a site should also disable the extension in all its frames.

**Comment by galambalazs** [comment]
cool
