### ISSUE TITLE
chrome for os x not need this

### ISSUE THREAD

**Issue by 499978920** [galambalazs/smoothscroll#116]
I use os x and win. this plugin is not necessary for os x,can you modify it to ignore for os x?

**Comment by galambalazs** [comment]
Chrome for OS X does need it (using your mouse wheel). 

What you may refer to is Touchpad scrolling. Did you try to disable that feature?

**Comment by galambalazs** [comment]
duplicate of https://github.com/galambalazs/smoothscroll/issues/65
