### ISSUE TITLE
Spacebar doesn't result in space character in input fields of any site, when keyboard support enabled

### ISSUE THREAD

**Issue by proteme** [galambalazs/smoothscroll#117]
When the keyboard support is enabled, pressing spacebar in any input field on any site does not result in space character being entered, instead it works to scroll the screen to the next page/view.

**Comment by galambalazs** [comment]
Thank I'll check, but I doubt it could happen because this case is handled specifically.
Are you sure this happens on every website, not just a particular one?

**Comment by proteme** [comment]
Yes, you are right. 

Right now I tested with several other sites and noticed this does not happen in other sites. 

I had noticed this on one of our internal sites and couple of others, which I don't remember. I suspected it to be due to some chrome extension. I sequentially disabled each of them until I identified Smooth Scroll as being responsible and then I narrowed it down to the Keyboard option. 

FWIW, I do not see any exceptions in chrome console.

**Comment by galambalazs** [comment]
I consider this solved.
If you can show a dummy page which demonstrates the problem I may be able to look at it.

**Comment by awls99** [comment]
I had this problem on the search bar of Youtube and on the name field of the add credit card of Amazon and other sites; found this thread, disabled keyboard support and it started working instantly (after page reload).

**Comment by galambalazs** [comment]
oops that was typo in a new update pushed today.
A fixed version is updated now.
