### ISSUE TITLE
Causes empty div with huge whitespace when developer tools are opened

### ISSUE THREAD

**Issue by planetmadness** [galambalazs/smoothscroll#120]
When the developer tools are opened and the page is refreshed. The extension creates an empty div at the bottom of the page which is the same size of the page itself, rendering a huge amount of empty whitespace at the bottom.

Steps to recreate this:

1. ensure the extension is installed and activated
2. open any page in google Chrome
3. scroll to the bottom to confirm there is no whitespace already present
4. open developer tools
5. refresh the page
6. scroll to the bottom of the page and check for whitespace

The empty div does not disappear when the developer tools are closed or the page is refreshed. The only solution is to open the page in a new tab.

**Comment by galambalazs** [comment]
Which page?
Chrome / Opera?

**Comment by galambalazs** [comment]
i cant reproduce
