### ISSUE TITLE
No scroll settings applied in Chrome PDF Viewer

### ISSUE THREAD

**Issue by Karut** [galambalazs/smoothscroll#121]
It the app description it says: "Works with embedded content (PDF, flash)", but my scroll settings certainly do not apply to the Chrome PDF Viewer. A bug or I am missing something here? If it's not a bug then this is a feature request :)

Using Chromium 46.0.2490.86 under Opensuse Tumbleweed KDE Plasma 5.

**Comment by galambalazs** [comment]
This is unfortunately not possible.

Works here means that it doesn't mess with embedded content (as flash games probably expect one scroll event in many cases)
