### ISSUE TITLE
Switching presets iPhone, IE, etc, option Custom gets stuck

### ISSUE THREAD

**Issue by dbeasy** [galambalazs/smoothscroll#125]
I like that popular scrolling "feel" presets are available, such as iPhone, IE, Opera. Minor bug, when "Custom" is clicked the other button presets stop working, e.g. click on IE preset animation time is set to 60ms, then iPhone animation time is 600ms and you can click back and forth to see how they compare. But once the Custom button is clicked you cannot click on IE or iPhone to see their built-in value anymore. 

Also the "Bug Report" link goes to the main github page for this project, not to the "/issues" page.

**Comment by galambalazs** [comment]
will be fixed in the next  version, thanks
