### ISSUE TITLE
Since today's update space was broken

### ISSUE THREAD

**Issue by iori3000** [galambalazs/smoothscroll#127]
Since today's update space function is little broken.

We can not input space in any form, for example we can not input space in this issue page's title form.
and it only scrolls where page can be scrolled even though cursor is in the form.

So we should turn off 'Enable keyboard support' in smoothscroll option.

**Comment by galambalazs** [comment]
fixed in the new version.
Thanks

**Comment by railsr** [comment]
Wanted to report that too but then just unchecked `Enable keyboard support` from the options.

**Comment by galambalazs** [comment]
check latest

**Comment by galambalazs** [comment]
reopen if you still find this bug happening
