### ISSUE TITLE
Not working on IE

### ISSUE THREAD

**Issue by VBGWeb** [galambalazs/smoothscroll#129]
On IE, the scrolling is really "jumpy".
I'm testing on IE 11. 
Works perfect on other browsers.

Is there a fix for that?

Couldn't find anything like this on the issues, so sorry if this was already reported!

**Comment by galambalazs** [comment]
Windows version?

**Comment by VBGWeb** [comment]
Windows 10 (Home)

**Comment by galambalazs** [comment]
The way it's currently set up is that it's only enabled for Windows 7 IE 11.

Windows 8 & 10 have built in "smooth" scrolling.

Now it's true that they may be jumpier (meaning the animation of one tick is shorter).
But it's still animated nonetheless.

The library is currently built in the spirit of not "breaking" native feel that users' are accustomed to when that scrolling is animated (even if the animation is not to my liking).

There may be an option for this later where you can on which browsers you want to enabled it.

For now what you can do is to change this line:
 https://github.com/galambalazs/smoothscroll-for-websites/blob/master/SmoothScroll.js#L690

from:
    var isIEWin7  = /Windows NT 6.1/i.test(userAgent) && /rv:11/i.test(userAgent);

to:
    var isIEWin7  = /rv:11/i.test(userAgent);

So it'll run on IE 11 no matter what the Windows version is.

Cheers
