### ISSUE TITLE
Chrome Flash Youtube Smooth Scrool

### ISSUE THREAD

**Issue by brioto** [galambalazs/smoothscroll#130]
Hi!

Scenario to reproduce the bug:

Chromium: any version
Youtube: play video with flash player, not by the default html5 player ( You can use the add on at https://chrome.google.com/webstore/detail/disable-youtube-html5-pla/enmofgaijnbjpblfljopnpdogpldapoc )
Smooth Scroll: 1.5.11 (Default settings)
Flash Player: 21.0.0.213

1-Load custom video from youtube.com, for example https://www.youtube.com/watch?v=Wji-BZ0oCwg
2-Try to scroll. Everything is fine;
3-Try to skip some time in the same video  and left click with the mouse to play the same video after 30 sec for example or right mouse click to see the flash version. Don't click anywhere else. The page is scrolling but Smooth Scroll is doesn't work, when I am scrolling the page.
4-If I click outsude the flash player in the video, the Smooth Scroll start working.

For my understanding there is focus issue between flash player in youtube.com and maybe other similar sites with the adobe player and Smooth Scroll.

**Comment by galambalazs** [comment]
This is intentional.
If you click a flash content SS leaves all scroll and key events alone
(Your flash player eg game or video may use those event)

If you click outside SS enables itself again
