### ISSUE TITLE
If you could make middle click paste work with your extension on Linux that would be great

### ISSUE THREAD

**Issue by person666** [galambalazs/smoothscroll#132]
I am currently using https://github.com/Pauan/AutoScroll, but it is not maintained and your extension seems better, however middle click pasting into non standard text boxes like YouTube comments, quora text boxes and google drive don't work with your extension. 

If there was an option to disable starting middle click scrolling when hovering over a HTML element of a class or id that would be great.

**Comment by galambalazs** [comment]
will be fixed in the next version. thanks
