### ISSUE TITLE
A version of the library prevents keyboard scrolling

### ISSUE THREAD

**Issue by smaug----** [galambalazs/smoothscroll#135]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1278101

I haven't yet debugged why keyboard scrolling is prevented (it is also prevent in Chrome when experimental web platform features are enabled).

**Comment by galambalazs** [comment]
I don't think you meant this library.

I checked the site: http://books.portonvictor.org/nt-commentary-online/index.html

And it has some other smooth scrolling script.

If you have any more info, let me know

**Comment by smaug----** [comment]
I'm pretty sure it is the same or a variant.
Compare its keydown handling to https://github.com/galambalazs/smoothscroll/blob/master/src/sscr.js#L365
