### ISSUE TITLE
After leaving a comment it is not working until minimizing and restoring in chrome

### ISSUE THREAD

**Issue by iori3000** [galambalazs/smoothscroll#136]
I am not sure which is exact problem between chrom and smoothscroll.
Sometimes smoothscroll is not working i mean scroll is not smoth.
But then if I mimimize chrome window and restore it, then it starts to work.

**Comment by galambalazs** [comment]
On what site or can you see this on All website?

**Comment by iori3000** [comment]
This is so rarely occured and not 100% and not a big problem. 
I suspected collision with smooth scroll functions of Chrome which was comming currently.
So I turned off all kinds of Chrome smooth scroll function in chrome://flags/
Then Currently I cannot see this issue again.
Or Chrome or this app is upgraded? Sorry, I am not sure.

**Comment by galambalazs** [comment]
Chrome receives regular updates.
This app is updated less recently.

**Comment by iori3000** [comment]
I got found something, it was occured after leaving comment in kind of YouTube or other sites I don't sure if it occures when writings take some long time or not.

**Comment by iori3000** [comment]
I got found something more.
Chrome also has smooth scrolling function integrated,
If we want to use this addon properly we should turn off Chrome integrated #smmoth-scrolling in chorme://flags because the integrated overrides this addon functions.
And i tested the integrated of Chrome, it has also same problem which is not working after leaving a comment.
