### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by raeesbhatti** [galambalazs/smoothscroll#140]
I see this error in console almost every time a new page is loaded. But its not there (most of the time) when you reload the same page. 

```
Uncaught TypeError: Cannot read property 'nodeName' of undefined
isNodeName @ sscr.js:570
wheel @ sscr.js:303
```

**Comment by galambalazs** [comment]
will be fixed in the new version
thanks
