### ISSUE TITLE
Returning to mouse wheel scrolling after a (precision) touchpad scroll with Touchpad Support disabled results in choppy scrolling steps

### ISSUE THREAD

**Issue by esidegallery** [galambalazs/smoothscroll#155]
I have a precision touchpad in Windows 10. In order to get the native feel of the touchpad in Chrome I need to disable the Touchpad Support option in SmoothScroll. However, if I scroll using the touchpad, then return to mouse wheel, the first 2 scroll steps aren't smooth. Thereafter smooth scrolling resumes.

**Comment by galambalazs** [comment]
That's cause the extension needs some samples to figure out you are scrolling w touchpad or mouse.

No access to hardware info so this simple testing is the only way.
