### ISSUE TITLE
Middle click scrolling is broken

### ISSUE THREAD

**Issue by Bullsquid** [galambalazs/smoothscroll#159]
I can no longer scroll with middle click: arrow cross appears, but page remains still and scrolling with mouse movement doesn't work.
Chrome on Linux, Version 61.0.3163.79 (Official Build) (64-bit)

**Comment by triwa** [comment]
seconded, on:
Version 61.0.3163.91 (Official Build) (64-bit)

**Comment by Bullsquid** [comment]
Also, everything works fine on Windows.

**Comment by sealj553** [comment]
I also have this issue using Chromium on Linux, Version 61.0.3163.91 (Developer Build) (64-bit)

**Comment by eonmachus** [comment]
Hello, great extension, the middle click worked awesome, but also fails on Opera(Chromium based) v48, since last upgrade, and since I used  linux Mint KDE 17.3 cannot rollback easly , would be great if could get it rock and rolling back again XD. cheers!

**Comment by dtapuska** [comment]
@galambalazs This is because the extension in the app store is still using an old method to determine the scrolling root. If the smoothscroll.js in the extension was actually matched to be the latest version in the repo it probably would work.

**Comment by friggit** [comment]
Still not working in Opera 48.0 on macOS 10.12.6. Is there a workaround or a fix in the works? It drives me crazy...

**Comment by Bullsquid** [comment]
@friggit you can disable middle click scrolling in SmoothScroll and move to some other extension for smooth scrolling, like AutoScroll.

**Comment by friggit** [comment]
@Bullsquid Thanks, but I checked alternatives before commenting. AutoScroll only works up to Opera 12 (https://addons.opera.com/en/extensions/details/autoscroll/). Then I searched addons.opera.com for "scroll" and tried out every extension with a description that sounded like it could provide middle click scrolling, but none did. It looks to me like SmoothScroll is the only option.

**Comment by robbyph** [comment]
I'm also having this issue

**Comment by galambalazs** [comment]
fixed guys, cheers
