### ISSUE TITLE
This extension will cause mouse gestures issues in cent browser

### ISSUE THREAD

**Issue by yokiding** [galambalazs/smoothscroll#163]
This extension will cause mouse gestures failure on back to the top of the page in cent browser，I hope you can fix it，many thanks.

**Comment by galambalazs** [comment]
Sorry only Chrome is supported.

**Comment by yokiding** [comment]
But Cent browser is a browser based on Chromium, and other extensions can be used normally.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Balázs Galambosi <notifications@github.com>
发送时间: Monday, July 16, 2018 8:34:49 PM
收件人: galambalazs/smoothscroll
抄送: yokiding; Author
主题: Re: [galambalazs/smoothscroll] This extension will cause mouse gestures issues in cent browser (#163)


Sorry only Chrome is supported.

―

**Comment by galambalazs** [comment]
There are tons of chromium based browsers.

it should not work differently 

can you check in Chrome?
