### ISSUE TITLE
How to make it work in local HTML page ?

### ISSUE THREAD

**Issue by abdulbadii** [galambalazs/smoothscroll#171]
Too bad to not work in local HTML page
How to make it work on local HTML page ?
even though I add URL up to be

   "permissions": [ "storage", "http://*/*", "https://*/*","file:///*/*","chrome://*" ]

and in content_script
    "matches": [ "http://*/*", "https://*/*", "ftp://*/*","file:///*/*","chrome://*" ]

still doesn't work... please help me, I really need great guidance !

**Comment by galambalazs** [comment]
https://stackoverflow.com/questions/8921436/how-to-allow-a-google-chrome-plugin-to-access-files-as-webpages
