### ISSUE TITLE
Page jumps to top/bottom on wheel click

### ISSUE THREAD

**Issue by augenleet** [galambalazs/smoothscroll#69]
At the exact moment of a wheel click (for auto scrolling) while moving the cursor either up or down, it can happen that the page jumps to the top or bottom (seems random).

**Comment by atrotors** [comment]
+1

**Comment by galambalazs** [comment]
What are your SS settings guys? Still not able to reproduce.

**Comment by galambalazs** [comment]
Fixed thanks to @atrotors 

Thanks guys for reporting! :)
