### ISSUE TITLE
On the Chrome Web Store there is SmoothScrool 1.3.3, here it's stuck on1.2.6

### ISSUE THREAD

**Issue by StatelessCat** [galambalazs/smoothscroll#97]
Hey,
Does this mean that your new versions (> 1.2.6) are not open source anymore ?

**Comment by galambalazs** [comment]
I had copycats in the Chrome Web Store, so in the interest of my users for now I suspended publishing updates here with the MIT license.

If you'd like to use my code on your website or themes, there's a version here: https://gist.github.com/galambalazs/6477177

The only restriction would be not to publish any extension for browsers or native application with this code.

I have a Mac OS version in the works which works system wide.
