### ISSUE TITLE
"conflict" with middle mouse button paste

### ISSUE THREAD

**Issue by mjbjr** [galambalazs/smoothscroll#98]
I appreciate this feature, but if you use middle mouse button pasting (standard in linux), when you're doing a paste it also jumps into smoothscroll and due to micro movement of the mouse during this procedure the page scrolls away from the point of the paste.  Very aggravating.  It would be nice if this extension would detect that the mouse is over a text input widget (others ?) and in such a case not go into smoothscroll mode when the middle mouse button is clicked.  Firefox smoothscrolling doesn't have this problem.

**Comment by galambalazs** [comment]
I think we have a case for this.

https://github.com/galambalazs/smoothscroll/blob/master/src/middlemouse.js#L23

Line 23, 59,  71-72

It checks for input and textarea elements.

Is it by any chance a contentEditable div that you see this problem on?

**Comment by galambalazs** [comment]
https://github.com/galambalazs/smoothscroll/issues/25

**Comment by galambalazs** [comment]
Do you still see this issue?
